package org.jetbrains.fortran.lang.types.ty

data class FortranArrayType(val base: FortranType, val shape: FortranArrayShape) : FortranType() {
    override fun toString(): String {
        return base.toString() + " array" + if (shape !== FortranUnknownShape) " of shape " + shape.toString() else ""
    }

    override fun equals(other: Any?): Boolean {
        if (other !is FortranArrayType) {
            return false
        }

        return base == other.base && shape == other.shape
    }

    // generated by IDEA
    override fun hashCode(): Int {
        var result = base.hashCode()
        result = 31 * result + shape.hashCode()
        return result
    }
}