<DIRECTIVE>#include</DIRECTIVE> 'include.f95'
!comment
<KEYWORD>data</KEYWORD> <IDENTIFIER>binary</IDENTIFIER> / B'101'/
<KEYWORD>data</KEYWORD> <IDENTIFIER>octal</IDENTIFIER>  / O'765'/
<KEYWORD>data</KEYWORD> <IDENTIFIER>hex</IDENTIFIER>    / Z'4'  /
<KEYWORD>real</KEYWORD> <IDENTIFIER>W</IDENTIFIER>(100,100)[0:2,*]
<KEYWORD>integer</KEYWORD>, <KEYWORD>dimension</KEYWORD>(2) :: <IDENTIFIER>array</IDENTIFIER> = (/ 1, 2 /)
<KEYWORD>logical</KEYWORD> <IDENTIFIER>b</IDENTIFIER> = .true.
<KEYWORD>format</KEYWORD> (1PE12.4, I10)
<KEYWORD>if</KEYWORD> (<IDENTIFIER>a</IDENTIFIER> .le. 10 .and. <IDENTIFIER>b</IDENTIFIER> > 12 .or. <IDENTIFIER>c</IDENTIFIER>)
   <IDENTIFIER>c</IDENTIFIER> = (12**2 + 12.3d0 < <IDENTIFIER>v</IDENTIFIER>%<IDENTIFIER>res</IDENTIFIER>) .eqv. .not. (<IDENTIFIER>a</IDENTIFIER> .definedoperator. <IDENTIFIER>b</IDENTIFIER>)
<KEYWORD>else</KEYWORD>
   <KEYWORD>write</KEYWORD>(*,*) "Test output"
<KEYWORD>endif</KEYWORD>
<DIRECTIVE>#ifdef</DIRECTIVE> DEBUG
  <CONDITIONALLY_NOT_COMPILED>printf("debug")</CONDITIONALLY_NOT_COMPILED>;
<DIRECTIVE>#endif</DIRECTIVE>
<KEYWORD>end</KEYWORD>